/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ptithcm.tn_csdlpt.view;

import com.ptithcm.tn_csdlpt.model.dto.Account;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author MINHDAT
 */
public class FrmMain extends javax.swing.JFrame {
    private PnlMenu pnlMenu;
    private CustomTabbedPane tabbedPaneWorkspace;
    private PnlStatusBar pnlStatusBar;

    /**
     * Creates new form FrmMain
     */
    public FrmMain(Account account) {
        initComponents();
        initMyComponents();
        hideComponent(account.getGroupName());
        updateStatusBarData(account);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuContainer = new javax.swing.JPanel();
        pnlWorkspaceContainer = new javax.swing.JPanel();
        pnlStatusbarContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMenuContainer.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlMenuContainer, java.awt.BorderLayout.NORTH);

        pnlWorkspaceContainer.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlWorkspaceContainer, java.awt.BorderLayout.CENTER);

        pnlStatusbarContainer.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlStatusbarContainer, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initMyComponents() {
//        Khởi tạo các component
        pnlMenu = new PnlMenu();
        tabbedPaneWorkspace = new CustomTabbedPane();
        pnlStatusBar = new PnlStatusBar();
        
//        Thêm các component vừa tạo vào các vùng chứa
        pnlMenuContainer.add(pnlMenu);
        pnlWorkspaceContainer.add(tabbedPaneWorkspace);
        pnlStatusbarContainer.add(pnlStatusBar);
    }
    
    //    Ẩn và hiện các chức năng ứng với các nhóm quyền tương ứng
    public void hideComponent(String groupName) {
        switch(groupName) {
            case "SINHVIEN":
                pnlMenu.getTabManager().removeTabAt(1);
                pnlMenu.getBtnExamCalendarRegister().setVisible(false);
                pnlMenu.getTabManager().removeTabAt(2);
                break;
            case "GIANGVIEN":
                pnlMenu.getBtnTeacherManage().setVisible(false);
                pnlMenu.getBtnStudentManage().setVisible(false);
                pnlMenu.getBtnClassroomManage().setVisible(false);
                pnlMenu.getBtnSubjectManage().setVisible(false);
                pnlMenu.getBtnReportExamCalendar().setVisible(false);
                break;
            case "TRUONG":
                pnlMenu.getBtnExamCalendarRegister().setVisible(false);
                pnlMenu.getBtnDoExam().setVisible(false);
                break;
            case "COSO":
                pnlMenu.getBtnExamCalendarRegister().setVisible(false);
                pnlMenu.getBtnDoExam().setVisible(false);
                break;
        }
    }
    
//    Cập nhật thông tin cho thanh trạng thái khi đăng nhập thành công
    public void updateStatusBarData(Account account) {
        pnlStatusBar.getLblUsername().setText(account.getUsername());
        pnlStatusBar.getLblFullName().setText(account.getFullName());
        pnlStatusBar.getLblGroupName().setText(account.getGroupName());
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
                    String formattedDateTime = simpleDateFormat.format(new Date());
                    pnlStatusBar.getLblNowDateTime().setText(formattedDateTime);
                    System.out.println(formattedDateTime);
                    try {
                        sleep(1);
                    } catch (Exception e) {
                    }
                }
            }
        };
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlMenuContainer;
    private javax.swing.JPanel pnlStatusbarContainer;
    private javax.swing.JPanel pnlWorkspaceContainer;
    // End of variables declaration//GEN-END:variables
}
