/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.tn_csdlpt.view;

import javax.swing.JLabel;

/**
 *
 * @author MINHDAT
 */
public class PnlManageBar extends javax.swing.JPanel {

    /**
     * Creates new form PnlManageBar
     */
    public PnlManageBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnSave = new javax.swing.JLabel();
        btnUndo = new javax.swing.JLabel();
        btnReload = new javax.swing.JLabel();
        btnExportFile = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24x24/plus.png"))); // NOI18N
        btnAdd.setText("Thêm");
        add(btnAdd);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24x24/edit.png"))); // NOI18N
        btnUpdate.setText("Chỉnh sửa");
        add(btnUpdate);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24x24/delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        add(btnDelete);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24x24/save.png"))); // NOI18N
        btnSave.setText("Ghi");
        add(btnSave);

        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24x24/undo.png"))); // NOI18N
        btnUndo.setText("Phục hồi");
        add(btnUndo);

        btnReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24x24/reload.png"))); // NOI18N
        btnReload.setText("Reload");
        add(btnReload);

        btnExportFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24x24/export.png"))); // NOI18N
        btnExportFile.setText("Xuất file");
        add(btnExportFile);
    }// </editor-fold>//GEN-END:initComponents

//    Getters and setters
    public JLabel getBtnAdd() {
        return btnAdd;
    }

    public void setBtnAdd(JLabel btnAdd) {
        this.btnAdd = btnAdd;
    }

    public JLabel getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JLabel btnDelete) {
        this.btnDelete = btnDelete;
    }

    public JLabel getBtnExportFile() {
        return btnExportFile;
    }

    public void setBtnExportFile(JLabel btnExportFile) {
        this.btnExportFile = btnExportFile;
    }

    public JLabel getBtnReload() {
        return btnReload;
    }

    public void setBtnReload(JLabel btnReload) {
        this.btnReload = btnReload;
    }

    public JLabel getBtnSave() {
        return btnSave;
    }

    public void setBtnSave(JLabel btnSave) {
        this.btnSave = btnSave;
    }

    public JLabel getBtnUndo() {
        return btnUndo;
    }

    public void setBtnUndo(JLabel btnUndo) {
        this.btnUndo = btnUndo;
    }

    public JLabel getBtnUpdate() {
        return btnUpdate;
    }

    public void setBtnUpdate(JLabel btnUpdate) {
        this.btnUpdate = btnUpdate;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnExportFile;
    private javax.swing.JLabel btnReload;
    private javax.swing.JLabel btnSave;
    private javax.swing.JLabel btnUndo;
    private javax.swing.JLabel btnUpdate;
    // End of variables declaration//GEN-END:variables
}
