/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.tn_csdlpt.view;

import javax.swing.JLabel;

/**
 *
 * @author MINHDAT
 */
public class PnlStatusBar extends javax.swing.JPanel {

    /**
     * Creates new form pnlMenu
     */
    public PnlStatusBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel33 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblGroupName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNowDateTime = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 2));

        lblUsername.setText("Mã: 001");
        lblUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel33.add(lblUsername);

        lblFullName.setText("Họ và tên: Lương Trang");
        lblFullName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel33.add(lblFullName);

        lblGroupName.setText("Nhóm quyền: Công ty");
        lblGroupName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel33.add(lblGroupName);

        add(jLabel33, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 2));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 2));

        jLabel2.setText("Time:");
        jPanel3.add(jLabel2);

        lblNowDateTime.setText("11:20 AM");
        jPanel3.add(lblNowDateTime);

        jPanel2.add(jPanel3);

        add(jPanel2, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

//    Getters and setters
    public JLabel getLblFullName() {
        return lblFullName;
    }

    public void setLblFullName(JLabel lblFullName) {
        this.lblFullName = lblFullName;
    }

    public JLabel getLblGroupName() {
        return lblGroupName;
    }

    public void setLblGroupName(JLabel lblGroupName) {
        this.lblGroupName = lblGroupName;
    }

    public JLabel getLblNowDateTime() {
        return lblNowDateTime;
    }

    public void setLblNowDateTime(JLabel lblNowDateTime) {
        this.lblNowDateTime = lblNowDateTime;
    }

    public JLabel getLblUsername() {
        return lblUsername;
    }

//    Getters and setters
    public void setLblUsername(JLabel lblUsername) {
        this.lblUsername = lblUsername;
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jLabel33;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGroupName;
    private javax.swing.JLabel lblNowDateTime;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
